/**
 * routes/report.js
 * Legal PDF report generation.
 *
 * GET /api/report/pdf  — Download a formatted PDF of all the user's evidence.
 *
 * The PDF includes:
 *   - Cover page with user details and generation timestamp
 *   - One section per evidence item with description, category, and legal timestamp
 *   - A disclaimer for court use
 *   - Deepfake scan results where applicable
 *
 * This is designed to be handed to a lawyer, police officer,
 * or the Communications Authority of Kenya as part of a formal complaint.
 */

const express = require('express');
const PDFDocument = require('pdfkit');
const Evidence = require('../models/Evidence');
const { protect } = require('../middleware/authMiddleware');

const router = express.Router();
router.use(protect);

// ── Colour palette matching SalamaNet branding ─────────────────────────────
const COLORS = {
  green:      '#0F6E56',
  greenLight: '#E1F5EE',
  red:        '#A32D2D',
  redLight:   '#FCEBEB',
  muted:      '#5F5E5A',
  border:     '#d3d1c7',
  text:       '#2C2C2A',
  white:      '#FFFFFF',
};

// ── Category labels ────────────────────────────────────────────────────────
const CAT_LABELS = {
  cyberstalking:   'Cyberstalking',
  deepfake:        'Deepfake / AI-generated image',
  nonconsensual:   'Non-consensual image sharing',
  harassment:      'Online harassment',
  threat:          'Threats & intimidation',
  other:           'Other',
};

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/report/pdf
// Generate and stream a PDF evidence report to the client
// ─────────────────────────────────────────────────────────────────────────────
router.get('/pdf', async (req, res) => {
  try {
    // Fetch all evidence for this user, oldest first (chronological order for report)
    const items = await Evidence.find({ userId: req.user._id }).sort({ createdAt: 1 });

    // Create a PDF document — A4 size
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Title: `SalamaNet Evidence Report — ${req.user.name}`,
        Author: 'SalamaNet Safety Toolkit',
        Subject: 'Technology-Facilitated Gender-Based Violence Evidence',
        Keywords: 'TFGBV, evidence, Kenya, cybersafety',
        Creator: 'SalamaNet v1.0',
      },
    });

    // Stream the PDF directly to the HTTP response
    const filename = `salamanet-evidence-${Date.now()}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    // ── PAGE 1: COVER ──────────────────────────────────────────────────────

    // Header bar
    doc.rect(0, 0, doc.page.width, 120).fill(COLORS.green);

    // Shield emoji substitute (circle with text)
    doc.circle(90, 60, 28).fill(COLORS.white);
    doc.fontSize(22).fillColor(COLORS.green).text('🛡', 78, 47);

    // Title
    doc.fontSize(26).fillColor(COLORS.white).font('Helvetica-Bold')
      .text('SalamaNet', 130, 30, { lineBreak: false });
    doc.fontSize(12).fillColor('rgba(255,255,255,0.85)').font('Helvetica')
      .text('Official Evidence Report', 130, 60);
    doc.fontSize(10).fillColor('rgba(255,255,255,0.7)')
      .text('Usalama wako, nguvu yako — Your safety, your strength', 130, 78);

    doc.moveDown(5);

    // Report metadata box
    const metaY = 150;
    doc.rect(60, metaY, doc.page.width - 120, 130)
      .fillAndStroke(COLORS.greenLight, COLORS.border);

    doc.fontSize(13).fillColor(COLORS.green).font('Helvetica-Bold')
      .text('Report Information', 80, metaY + 16);

    const metaLines = [
      ['Prepared for',  req.user.name],
      ['Email',         req.user.email],
      ['Generated',     new Date().toLocaleString('en-KE', { dateStyle: 'full', timeStyle: 'medium' })],
      ['Total items',   `${items.length} evidence ${items.length === 1 ? 'item' : 'items'}`],
      ['Reference ID',  `SN-${Date.now()}`],
    ];

    let lineY = metaY + 36;
    doc.fontSize(10).font('Helvetica');
    for (const [label, value] of metaLines) {
      doc.fillColor(COLORS.muted).text(`${label}:`, 80, lineY, { continued: true, width: 120 });
      doc.fillColor(COLORS.text).text(value, { width: 300 });
      lineY += 16;
    }

    // Legal disclaimer box
    doc.moveDown(2);
    doc.rect(60, doc.y, doc.page.width - 120, 90)
      .fillAndStroke('#FAEEDA', '#fac775');

    doc.fontSize(10).fillColor('#633806').font('Helvetica-Bold')
      .text('⚠️  Legal Notice', 80, doc.y - 82);
    doc.font('Helvetica').fontSize(9)
      .text(
        'This document has been generated by the SalamaNet Safety Toolkit and contains ' +
        'digital evidence relating to Technology-Facilitated Gender-Based Violence (TFGBV). ' +
        'All timestamps are recorded in East Africa Time (UTC+3). This report may be submitted ' +
        'to the Communications Authority of Kenya, Kenya Police, or legal counsel as supporting ' +
        'documentation. Do not alter this document.',
        80, doc.y - 64, { width: doc.page.width - 160, lineGap: 3 }
      );

    // Emergency contacts section
    doc.moveDown(3);
    doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold').text('Kenya Support Resources');
    doc.fontSize(9).font('Helvetica').fillColor(COLORS.muted).moveDown(0.3)
      .text('Gender Violence Helpline: 0800 720 592 (free, 24/7)', { lineGap: 2 })
      .text('Kenya Police: 999 / 112', { lineGap: 2 })
      .text('Communications Authority of Kenya: +254 20 4242000', { lineGap: 2 })
      .text('Childline Kenya: 116 (under 18)', { lineGap: 2 });

    // ── SUBSEQUENT PAGES: EVIDENCE ITEMS ──────────────────────────────────

    if (items.length === 0) {
      doc.addPage();
      doc.fontSize(16).fillColor(COLORS.muted).font('Helvetica')
        .text('No evidence items have been stored yet.', { align: 'center' });
      doc.fontSize(12).fillColor(COLORS.muted)
        .text('Use the SalamaNet app to upload screenshots and files.', { align: 'center' });
    } else {
      items.forEach((item, index) => {
        doc.addPage();

        // Item header bar
        const isDeepfake = item.deepfakeResult === 'fake';
        const headerColor = item.isDeepfakeScan
          ? (isDeepfake ? COLORS.red : COLORS.green)
          : COLORS.green;

        doc.rect(0, 0, doc.page.width, 50).fill(headerColor);
        doc.fontSize(13).fillColor(COLORS.white).font('Helvetica-Bold')
          .text(`Evidence Item ${index + 1} of ${items.length}`, 60, 14);
        doc.fontSize(10).fillColor('rgba(255,255,255,0.8)').font('Helvetica')
          .text(CAT_LABELS[item.category] || item.category, 60, 32);

        // If deepfake result — show banner
        if (item.isDeepfakeScan && item.deepfakeResult) {
          const bannerColor = isDeepfake ? '#FCEBEB' : '#E1F5EE';
          const bannerBorder = isDeepfake ? '#f7c1c1' : '#9FE1CB';
          const bannerText = isDeepfake ? '#A32D2D' : '#085041';
          const verdict = isDeepfake ? '⚠️ POTENTIAL DEEPFAKE DETECTED' : '✅ MEDIA APPEARS AUTHENTIC';

          doc.rect(60, 65, doc.page.width - 120, 36)
            .fillAndStroke(bannerColor, bannerBorder);
          doc.fontSize(11).fillColor(bannerText).font('Helvetica-Bold')
            .text(verdict, 80, 76, { lineBreak: false });
          if (item.deepfakeConfidence) {
            doc.fontSize(10).font('Helvetica').fillColor(bannerText)
              .text(`  (${item.deepfakeConfidence}% confidence)`, { continued: false });
          }
        }

        // Evidence details table
        const tableY = item.isDeepfakeScan ? 115 : 75;
        const details = [
          ['File name',       item.fileName || 'Text record'],
          ['Category',        CAT_LABELS[item.category] || item.category],
          ['Recorded at',     new Date(item.createdAt).toLocaleString('en-KE', { dateStyle: 'full', timeStyle: 'long' })],
          ['Evidence ID',     item._id.toString()],
          ['File size',       item.fileSize > 0 ? `${(item.fileSize / 1024).toFixed(1)} KB` : 'N/A'],
          ['Type',            item.mimeType || 'Text / manual entry'],
        ];

        if (item.deepfakeResult) {
          details.push(['Deepfake result',     item.deepfakeResult === 'fake' ? 'POTENTIAL DEEPFAKE' : 'Likely authentic']);
          details.push(['Analysis confidence', item.deepfakeConfidence ? `${item.deepfakeConfidence}%` : 'N/A']);
        }

        let rowY = tableY;
        doc.fontSize(10).font('Helvetica');
        for (const [label, value] of details) {
          // Alternating row shading
          if (details.indexOf([label, value]) % 2 === 0) {
            doc.rect(60, rowY - 4, doc.page.width - 120, 18).fill('#f8faf9');
          }
          doc.fillColor(COLORS.muted).font('Helvetica-Bold')
            .text(`${label}:`, 70, rowY, { continued: true, width: 140 });
          doc.fillColor(COLORS.text).font('Helvetica')
            .text(value, { width: doc.page.width - 280 });
          rowY += 20;
        }

        // Description box
        doc.moveDown(1);
        doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold').text('Description / Incident Account:');
        doc.moveDown(0.3);
        doc.rect(60, doc.y, doc.page.width - 120, 1).fill(COLORS.border); // divider
        doc.moveDown(0.5);
        doc.fontSize(10).fillColor(COLORS.text).font('Helvetica')
          .text(item.description, {
            width: doc.page.width - 120,
            lineGap: 4,
            paragraphGap: 6,
          });

        // Chain of custody note
        doc.moveDown(2);
        doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica-Oblique')
          .text(
            `Chain of custody: This record was created by user ID ${item.userId} on ` +
            `${new Date(item.createdAt).toISOString()} and has not been altered since storage. ` +
            `Evidence ID: ${item._id}`,
            { lineGap: 3 }
          );

        // Page footer
        doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica')
          .text(
            `SalamaNet Evidence Report • Page ${index + 2} • Generated ${new Date().toISOString()}`,
            60,
            doc.page.height - 40,
            { align: 'center', width: doc.page.width - 120 }
          );
      });
    }

    // Finalize the PDF — this sends it to the response
    doc.end();

  } catch (err) {
    console.error('PDF generation error:', err);
    // Can't set headers once streaming has started, so just log
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF report. Please try again.' });
    }
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/report/summary
// Returns a JSON summary of stats — used by the Profile page
// ─────────────────────────────────────────────────────────────────────────────
router.get('/summary', async (req, res) => {
  try {
    const items = await Evidence.find({ userId: req.user._id });

    const summary = {
      totalEvidence:   items.length,
      deepfakeScans:   items.filter(i => i.isDeepfakeScan).length,
      deepfakesFound:  items.filter(i => i.deepfakeResult === 'fake').length,
      byCategory:      {},
      oldestItem:      null,
      newestItem:      null,
    };

    // Count by category
    for (const item of items) {
      summary.byCategory[item.category] = (summary.byCategory[item.category] || 0) + 1;
    }

    if (items.length > 0) {
      const sorted = items.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
      summary.oldestItem = sorted[0].createdAt;
      summary.newestItem = sorted[sorted.length - 1].createdAt;
    }

    res.json({ summary });
  } catch (err) {
    console.error('Summary error:', err);
    res.status(500).json({ error: 'Failed to generate summary.' });
  }
});

module.exports = router;
